version: '3.8'
services:
  database:
    image: mysql:latest
    container_name: mysql
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'employee_management_system'
    ports:
      - "3306:3306"
volumes:
  mysql_compose_volume:
